name: Correctness Checks
on: [push, pull_request]
jobs:
  Run-Markdown-Checks:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "tools/requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
      - name: inspect_links
        run: python3 tools/inspect_links.py --num-warn 5
      - name: inspect_markdown
        run: python3 tools/inspect_markdown.py --num-recent 5
